-- =============================================================================
-- V1__init.sql
-- 저장 계층 스키마 (구버전 SQLite → PostgreSQL 이관)
--
-- 구버전(services/store.py)은 SQLite 파일 하나에 네 종류의 데이터를 담았습니다.
--   snapshots            "최신 상태" 1건 (매크로 카드, 13F, COT …)
--   timeseries           (데이터셋, 시리즈, 날짜) → 값
--   observations         (데이터셋, 날짜, 종목) → 레코드
--   collector_runs       수집 실행 로그 (PID·heartbeat)
--   collector_task_runs  태스크별 결과 (상태·소요시간·실패 이유)
--
-- 이 구조를 그대로 옮기되, 다음을 PostgreSQL 기능으로 바꿉니다.
--   - payload TEXT(JSON 문자열) → JSONB (백엔드가 SQL로 직접 질의 가능)
--   - collected_at TEXT(ISO 문자열) → TIMESTAMPTZ (신선도 계산이 SQL에서 가능)
--   - WAL 모드로 처리하던 동시성 → PostgreSQL MVCC (수집기 쓰기와 API 읽기가
--     서로를 막지 않는다는 성질은 동일합니다)
--
-- ⚠️ 추정치(is_estimated=true)는 누적 테이블(timeseries/observations)에 넣지
--    않는다는 구버전 규칙을 그대로 유지합니다. 한 번 섞이면 실제 확정치와
--    구분할 수 없기 때문입니다. 이 규칙은 수집기 코드에서 강제합니다.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. 스냅샷: "최신 상태" 1건
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS snapshots (
    name         TEXT PRIMARY KEY,
    payload      JSONB       NOT NULL,
    kind         TEXT        NOT NULL DEFAULT 'json',   -- json | frame | object
    status       TEXT        NOT NULL DEFAULT 'ok',     -- ok | estimated | error
    error        TEXT,
    collected_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE  snapshots IS '데이터셋별 최신 수집 결과 1건 (구버전 SQLite snapshots 테이블과 동일 역할)';
COMMENT ON COLUMN snapshots.status IS 'ok=확정치, estimated=추정치(화면에 경고 필요), error=수집 실패';

CREATE INDEX IF NOT EXISTS idx_snapshots_collected_at ON snapshots (collected_at DESC);

-- -----------------------------------------------------------------------------
-- 2. 시계열 누적: (데이터셋, 시리즈, 날짜) → 값
--    FRED / KRX 선물 / 연준 순유동성이 여기에 쌓입니다.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS timeseries (
    dataset    TEXT        NOT NULL,
    series_id  TEXT        NOT NULL,
    obs_date   DATE        NOT NULL,
    value      DOUBLE PRECISION,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (dataset, series_id, obs_date)
);

CREATE INDEX IF NOT EXISTS idx_timeseries_lookup
    ON timeseries (dataset, series_id, obs_date);

-- -----------------------------------------------------------------------------
-- 3. 레코드 누적: (데이터셋, 날짜, 엔티티) → JSON 레코드
--    Naver/Daum/KRX는 과거 날짜 조회를 지원하지 않습니다. 수집할 때마다
--    거래일별로 쌓아 두는 것이 곧 백업입니다.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS observations (
    dataset    TEXT        NOT NULL,
    obs_date   DATE        NOT NULL,
    entity     TEXT        NOT NULL,
    payload    JSONB       NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (dataset, obs_date, entity)
);

CREATE INDEX IF NOT EXISTS idx_observations_lookup
    ON observations (dataset, obs_date DESC);

-- 수급 레이더 이력은 (시장/투자주체/매매구분)으로 걸러 읽습니다.
CREATE INDEX IF NOT EXISTS idx_observations_radar_filter
    ON observations USING GIN (payload jsonb_path_ops);

-- -----------------------------------------------------------------------------
-- 4. 수집 실행 로그
--    PID·heartbeat를 남기는 이유: 수집기가 강제 종료되면 status가 'running'에
--    영구히 남아 "진행 중"이라고 거짓 보고합니다. 살아 있는지 판정하려면
--    프로세스 식별자와 마지막 신호 시각이 필요합니다.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS collector_runs (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at  TIMESTAMPTZ,
    status       TEXT        NOT NULL,     -- running | ok | partial | fail | interrupted
    ok_count     INTEGER     NOT NULL DEFAULT 0,
    fail_count   INTEGER     NOT NULL DEFAULT 0,
    detail       TEXT,
    pid          INTEGER,
    host         TEXT,
    heartbeat_at TIMESTAMPTZ,
    group_name   TEXT
);

CREATE INDEX IF NOT EXISTS idx_collector_runs_started
    ON collector_runs (started_at DESC);

-- -----------------------------------------------------------------------------
-- 5. 태스크별 실행 결과
--    집계(성공 N·실패 M)만 있으면 "무엇이 왜 실패했는지" 알 수 없습니다.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS collector_task_runs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id      BIGINT REFERENCES collector_runs (id) ON DELETE SET NULL,
    task        TEXT        NOT NULL,
    speed       TEXT,                       -- fast | slow | weekly
    status      TEXT        NOT NULL,       -- ok | empty | error
    started_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    duration_ms INTEGER,
    detail      TEXT
);

CREATE INDEX IF NOT EXISTS idx_task_runs_task ON collector_task_runs (task, id DESC);
CREATE INDEX IF NOT EXISTS idx_task_runs_run  ON collector_task_runs (run_id);

-- -----------------------------------------------------------------------------
-- 6. 수동 새로고침 기준 시각
--    구버전은 이 값을 Streamlit 프로세스의 전역 변수(_refresh_token)로 들고
--    있었습니다. 프로세스가 분리된 지금은 프로세스 메모리에 둘 수 없어
--    (백엔드·수집기가 서로 다른 컨테이너) 공유 테이블에 둡니다.
--
--    "저장본을 지운다"가 아니라 "이 시각 이전 저장본은 낡은 것으로 본다"는
--    기준을 세우는 방식은 구버전과 동일합니다. 수집이 실패해도 기존 저장본을
--    계속 보여줄 수 있어야 하기 때문입니다.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS refresh_requests (
    scope         TEXT PRIMARY KEY,          -- 'global' 또는 스냅샷 이름
    requested_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
